In [2]:
import numpy as np
S = np.array([[1, 0, 1],
              [1, 1, 0],
              [0, 1, 1]])

# Basis vectors for C̃ (4x4)
T = np.array([[1, 0, 1, 0],
              [1, 1, 0, 0],
              [0, 1, 1, 0],
              [0, 0, 0, 1]])

print("S =\n", S)
print("T =\n", T)

S =
 [[1 0 1]
 [1 1 0]
 [0 1 1]]
T =
 [[1 0 1 0]
 [1 1 0 0]
 [0 1 1 0]
 [0 0 0 1]]


In [3]:
T_inv = np.linalg.inv(T)
print("T⁻¹ =\n", T_inv)

T⁻¹ =
 [[ 0.5  0.5 -0.5  0. ]
 [-0.5  0.5  0.5  0. ]
 [ 0.5 -0.5  0.5  0. ]
 [ 0.   0.   0.   1. ]]


In [4]:
# Original transformation matrix AΦ (4x3)
A_phi = np.array([[ 2,  3,  1],
                  [ 0,  2,  4],
                  [ 4,  6,  2],
                  [-2,  1,  3]])

# Compute ÃΦ = T⁻¹ @ AΦ @ S
temp = A_phi @ S
print(f"temp :\n {temp}\n")

A_phi_tilde = T_inv @ temp
print("ÃΦ =\n", A_phi_tilde)

temp :
 [[ 5  4  3]
 [ 2  6  4]
 [10  8  6]
 [-1  4  1]]

ÃΦ =
 [[-1.5  1.   0.5]
 [ 3.5  5.   3.5]
 [ 6.5  3.   2.5]
 [-1.   4.   1. ]]


In [5]:
import numpy as np

# Original transformation matrix
A_phi = np.array([
    [2, 3, 1],
    [0, 2, 4],
    [4, 6, 2],
    [-2, 1, 3]
])

# Change of basis matrix for domain (S)
S = np.array([
    [1, 0, 1],
    [1, 1, 0],
    [0, 1, 1]
])

# Change of basis matrix for codomain (T)
T = np.array([
    [1, 0, 1, 0],
    [1, 1, 0, 0],
    [0, 1, 1, 0],
    [0, 0, 0, 1]
])

# Calculate the new transformation matrix
T_inv = np.linalg.inv(T)
A_phi_new = T_inv @ A_phi @ S

print("New transformation matrix Ã_φ:")
print(A_phi_new)

New transformation matrix Ã_φ:
[[-1.5  1.   0.5]
 [ 3.5  5.   3.5]
 [ 6.5  3.   2.5]
 [-1.   4.   1. ]]
