In [1]:
import numpy as np

# 행렬 A (3x3) 정의
A = np.array([
    [2, 1, -1],
    [-3, -1, 2],
    [-2, 1, 2]
])

# 벡터 B 정의
B = np.array([8, -11, -3])

# 해 x 계산: x = A⁻¹B 또는 np.linalg.solve 사용
x = np.linalg.solve(A, B)

# 결과 출력
print("해 x:")
print(x)


해 x:
[ 2.  3. -1.]


In [3]:
A_inv = np.linalg.inv(A)
print(f"A_inv : {A_inv}")

A_inv : [[ 4.  3. -1.]
 [-2. -2.  1.]
 [ 5.  4. -1.]]


In [4]:
X = A_inv @ B
print(f"X = {X}")

X = [ 2.  3. -1.]
